# Generated by Django 2.2.7 on 2020-12-20 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kitchens', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='vendor',
            new_name='kitchen',
        ),
    ]
