# Generated by Django 2.2.7 on 2020-12-27 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchens', '0003_kitchen_daily_order_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ticket_num',
            field=models.CharField(default='0000', max_length=255),
        ),
    ]
