# Generated by Django 2.2.4 on 2020-08-20 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20200820_1748'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='auth_level',
            new_name='user_level',
        ),
    ]
